// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Canvas from "./islands/Canvas.tsx";
import * as $Match from "./islands/Match.tsx";
import * as $NameInput from "./islands/NameInput.tsx";
import * as $TeamInput from "./islands/TeamInput.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Canvas.tsx": $Canvas,
    "./islands/Match.tsx": $Match,
    "./islands/NameInput.tsx": $NameInput,
    "./islands/TeamInput.tsx": $TeamInput,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
